<div id="eg1" data-mage-init='{"Suraj_JSExample/js/dynamic-content":{"ajaxContent":true,"saveState":true,"animate":700}}'>
	<div data-role="title">
		<h2>How 's bout a collapsible widget?<button data-role="trigger">Go</button></h2>
	</div>
	<div data-role="content">
		<a href="<?= $block->getViewFileUrl('Suraj_JSExample/collapsible-content.html')?>" data-ajax="true"></a>
	</div>
</div>
<div id="eg2" data-mage-init='{"Suraj_JSExample/js/dynamic-content":{"ajaxContent":true,"saveState":true,"animate":700}}'>
	<div data-role="title">
		<h2>How 's bout a collapsible widget?<button data-role="trigger">Go</button></h2>
	</div>
	<div data-role="content">
		<a href="<?= $block->getViewFileUrl('Suraj_JSExample/collapsible-content.html')?>" data-ajax="true"></a>
	</div>
</div>
<div id="eg3" data-mage-init='{"Suraj_JSExample/js/dynamic-content":{"ajaxContent":true,"saveState":true,"animate":700}}'>
	<div data-role="title">
		<h2>How 's bout a collapsible widget?<button data-role="trigger">Go</button></h2>
	</div>
	<div data-role="content">
		<a href="<?= $block->getViewFileUrl('Suraj_JSExample/collapsible-content.html')?>" data-ajax="true"></a>
	</div>
</div>